schema_version = "0.0.4"

id = "pes"
version = "0.0.4"
name = "Poba e Sagu"
tagline = "Addon para o projeto Poba e Sagu - Histeria.studios"
type = "add-on"

maintainer = "Igor Muniz"
website = "site.com"
tags = ["Animação", "Rig"]

blender_version_min = "4.3.0"

# License conforming to https://spdx.org/licenses/ (use "SPDX: prefix)
# https://docs.blender.org/manual/en/dev/advanced/extensions/licenses.html
license = [
  "SPDX:GPL-3.0-or-later",
]

copyright = [
  "2025 Igor Muniz, Histeria Studios",
]

[permissions]
files = "Save txt files to disk"
